### ISSUE TITLE
Не запускается проект

### ISSUE THREAD

**Issue by Greyewi** [maxfarseer/redux-ru-tutorial#6]
Прохожу ваш курс и ошибка появилась на данном моменте 
https://maxfarseer.gitbooks.io/redux-course-ru/content/es2015,_react_hmr.html
При запуске npm start выдает 

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.loaders[0] has an unknown property 'plugins'. These properties are valid:
   object { enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, query?, resource?, resourceQuery?, compiler?, rules?, test?, use? }
    at webpack (D:\PROJECTS\redux-tutorial\node_modules\webpack\lib\webpack.js:19:9)
    at Object.<anonymous> (D:\PROJECTS\redux-tutorial\server.js:9:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redux-tutorial@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the redux-tutorial@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redux-tutorial package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redux-tutorial
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redux-tutorial
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Greyewi\AppData\Roaming\npm-cache\_logs\2017-06-28T18_26_21_343Z-debug.log

**Comment by Elvaleryo** [comment]
преустанови webpack на более раннюю версию
 npm uninstall webpack --save-dev
npm install webpack@2.1.0-beta.22 --save-dev

**Comment by martrix78** [comment]
и получаем следующую ошибку 
`ERROR in ./src/index.js
Module build failed: TypeError: fileSystem.statSync is not a function
    at module.exports (/var/www/react/node_modules/babel-loader/lib/utils/exists.js:7:25)
    at find (/var/www/react/node_modules/babel-loader/lib/resolve-rc.js:13:9)
    at Object.module.exports (/var/www/react/node_modules/babel-loader/lib/index.js:113:132)
 @ multi main
`
